# Generated by Django 5.2.9 on 2025-12-24 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BagObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Imported identifier for the BAG object.",
                        max_length=255,
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="The address of the BAG object.",
                        max_length=80,
                        verbose_name="address",
                    ),
                ),
            ],
            options={
                "verbose_name": "BAG object",
                "verbose_name_plural": "BAG objects",
            },
        ),
        migrations.CreateModel(
            name="ContainerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="The type of the container.",
                        max_length=120,
                        unique=True,
                        verbose_name="type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The description of the container.",
                        verbose_name="description",
                    ),
                ),
            ],
            options={
                "verbose_name": "container type",
                "verbose_name_plural": "container types",
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Imported identifier for the entity (subject).",
                        max_length=255,
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "bsn",
                    models.CharField(
                        blank=True,
                        help_text="The BSN of the entity (subject).",
                        max_length=9,
                        verbose_name="bsn",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the entity (subject), this can be a person, organisation, company, etc.",
                        max_length=120,
                        verbose_name="name",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="The address of the entity (subject).",
                        max_length=120,
                        verbose_name="address",
                    ),
                ),
                (
                    "postcode_city",
                    models.CharField(
                        blank=True,
                        help_text="The postcode with the city/town of the entity (subject).",
                        max_length=120,
                        verbose_name="postcode + city",
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True,
                        help_text="The postcode of the entity (subject).",
                        max_length=6,
                        verbose_name="postcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "entity",
                "verbose_name_plural": "entities",
            },
        ),
        migrations.CreateModel(
            name="Fraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Imported identifier for the Fraction.",
                        max_length=255,
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="The description of the Fraction.",
                        verbose_name="description",
                    ),
                ),
            ],
            options={
                "verbose_name": "faction",
                "verbose_name_plural": "fractions",
            },
        ),
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Imported identifier for the Container.",
                        max_length=255,
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "is_collection_container",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the container has a collection container.",
                        verbose_name="is collection container",
                    ),
                ),
                (
                    "has_key",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the container has a key.",
                        verbose_name="has a key",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="The type of the container.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trash.containertype",
                        verbose_name="type",
                    ),
                ),
            ],
            options={
                "verbose_name": "container",
                "verbose_name_plural": "containers",
            },
        ),
        migrations.CreateModel(
            name="EntityObjectManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Imported identifier for the entity linked to BAG object.",
                        max_length=255,
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="The start date of when the entity (subject) is in use of the BAG object.",
                        null=True,
                        verbose_name="start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="The date of when the entity (subject) is no longer in use of the BAG object.",
                        null=True,
                        verbose_name="end date",
                    ),
                ),
                (
                    "bag_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trash.bagobject",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trash.entity"
                    ),
                ),
            ],
            options={
                "verbose_name": "entity object management",
                "verbose_name_plural": "entity object managements",
            },
        ),
        migrations.CreateModel(
            name="Emptying",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Imported identifier for the Emptying.",
                        max_length=255,
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "weight_dispersed",
                    models.CharField(
                        blank=True,
                        help_text="The dispersed weight of the container that got dumped.",
                        max_length=20,
                        verbose_name="weight dispersed",
                    ),
                ),
                (
                    "weight_none_dispersed",
                    models.CharField(
                        blank=True,
                        help_text="The none dispersed weight of the container that got dumped.",
                        max_length=20,
                        verbose_name="weight none dispersed",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        default=1,
                        help_text="The amount of times the container needed to be dumped to empty.",
                        verbose_name="amount",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="The date of the emptying.", verbose_name="date"
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        help_text="The datetime of the emptying.",
                        verbose_name="datetime",
                    ),
                ),
                (
                    "cost_per_kilo",
                    models.FloatField(
                        default=0.0,
                        help_text="The cost per kilo of weight dumped.",
                        verbose_name="cost per kilo",
                    ),
                ),
                (
                    "cost_per_emptying",
                    models.FloatField(
                        default=0.0,
                        help_text="The cost of this specific emptying.",
                        verbose_name="cost per emptying",
                    ),
                ),
                (
                    "share_factor",
                    models.IntegerField(
                        default=1,
                        help_text="The factor the emptying is shared among entities.",
                        verbose_name="share factor",
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        help_text="The container which was emptied.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trash.container",
                        verbose_name="container",
                    ),
                ),
                (
                    "entity_object_management",
                    models.ManyToManyField(
                        help_text="The entity/object connection that this emptying is tied to.",
                        to="trash.entityobjectmanagement",
                        verbose_name="entity/object management",
                    ),
                ),
            ],
            options={
                "verbose_name": "emptying",
                "verbose_name_plural": "emptying's",
            },
        ),
        migrations.AddField(
            model_name="containertype",
            name="fraction",
            field=models.ForeignKey(
                help_text="The fraction of the container.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trash.fraction",
                verbose_name="fraction",
            ),
        ),
    ]
