# Generated by Django 5.2.9 on 2026-01-21 10:30

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
import vng_api_common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='gewijzigd op')),
                ('afval_type', models.CharField(choices=[('gft', 'Groente, Fruit en Tuin afval (GFT)'), ('restafval', 'Rest afval (Rest)')], help_text='Het type afval dat de container bevat', max_length=20, verbose_name='afvaltype')),
                ('is_verzamelcontainer', models.BooleanField(default=False, help_text='Of de container een verzamelcontainer is.', verbose_name='is verzamelcontainer')),
                ('heeft_sleutel', models.BooleanField(default=False, help_text='Of de container een sleutel heeft.', verbose_name='heeft sleutel')),
            ],
            options={
                'verbose_name': 'container',
                'verbose_name_plural': 'containers',
            },
        ),
        migrations.CreateModel(
            name='ContainerLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='gewijzigd op')),
                ('adres', models.CharField(blank=True, help_text='Het adres van een afval container.', max_length=80, verbose_name='adres')),
            ],
            options={
                'verbose_name': 'Locatie van een afval container',
            },
        ),
        migrations.CreateModel(
            name='Klant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='gewijzigd op')),
                ('bsn', vng_api_common.fields.BSNField(help_text='De BSN van de klant.', max_length=9, unique=True, verbose_name='bsn')),
                ('naam', models.CharField(blank=True, help_text='De naam van de klant, dit kan een persoon, organisatie, bedrijf, etc. zijn.', max_length=120, verbose_name='naam')),
            ],
            options={
                'verbose_name': 'eigenaar',
                'verbose_name_plural': 'eigenaren',
            },
        ),
        migrations.CreateModel(
            name='Lediging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='gewijzigd op')),
                ('gewicht', models.FloatField(help_text='De gewicht van de lediging.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='gewicht')),
                ('geleegd_op', models.DateTimeField(help_text='De datum en tijd van de lediging.', verbose_name='geleegd op')),
                ('geleegd_op_datum', models.GeneratedField(db_index=True, db_persist=True, expression=django.db.models.functions.datetime.TruncDate('geleegd_op'), output_field=models.DateField())),
                ('container', models.ForeignKey(help_text='De container die geleegd is.', on_delete=django.db.models.deletion.CASCADE, related_name='ledigingen', to='afval.container', verbose_name='container')),
                ('container_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledigingen', to='afval.containerlocation', verbose_name='container location')),
                ('klant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledigingen', to='afval.klant', verbose_name='klant')),
            ],
            options={
                'verbose_name': 'lediging',
                'verbose_name_plural': 'ledigingen',
            },
        ),
    ]
