# Generated by Django 5.2.9 on 2026-06-23 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afval", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lediging",
            name="kosten",
            field=models.FloatField(
                default=0,
                help_text="De kosten van de lediging",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="kosten",
            ),
        ),
    ]
