# Generated by Django 5.2.15 on 2026-07-01 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afval", "0003_container_public_container_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lediging",
            name="kosten",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="De kosten van de lediging",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="kosten",
            ),
        ),
    ]
