# Generated by Django 5.2.9 on 2026-07-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afval', '0004_lediging_kosten_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='afval_type',
            field=models.CharField(choices=[('gft', 'Groente, Fruit en Tuin afval (GFT)'), ('restafval', 'Rest afval (Rest)'), ('med', 'Medisch afval')], help_text='Het type afval dat de container bevat', max_length=20, verbose_name='afvaltype'),
        ),
    ]
