# Generated by Django 5.2.9

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afval', '0007_lediging_klant_datum_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klant',
            options={'permissions': [('view_afval_profiel', 'Can view afval profiel')], 'verbose_name': 'eigenaar', 'verbose_name_plural': 'eigenaren'},
        ),
    ]
