# Generated by Django 5.2.17 on 2026-09-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afval', '0008_alter_klant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klant',
            options={'permissions': [('view_afval_profiel', 'Can view afval profiel')], 'verbose_name': 'klant', 'verbose_name_plural': 'klanten'},
        ),
    ]
