# Generated by Django 5.2.15 on 2026-09-29 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afval", "0009_alter_klant_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lediging",
            name="gewicht",
            field=models.DecimalField(
                decimal_places=2,
                help_text="De gewicht van de lediging.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="gewicht",
            ),
        ),
    ]
